version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  tag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Tag version
          command: npm version patch -m "[skip ci] Release patch version v%s"
      - run:
          name: Push tag to repo
          command: git push

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - tag
          filters:
            branches:
              only: master
