version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  tag:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      # Local CLI setup to commit and push to Github
      - run:
          name: Config Git user email
          command: git config user.email `git show -s --format='%ae' HEAD`
      - run:
          name: Config Git user name
          command: git config user.name `git show -s --format='%an' HEAD`
      - run:
          name: Add Github as a trusted host
          command: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "25:65:b8:b6:1d:a9:39:77:59:2e:ac:23:eb:77:49:97"

      - run:
          name: Tag version
          command: npm version patch -m "[skip ci] Release patch version v%s"
      - run:
          name: Push version commit to repo
          command: git push
      - run:
          name: Push tag to repo
          command: git push --tags

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - tag:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - tag
          filters:
            branches:
              only: master
